### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Anonymous941** [TehFridge/ShutTheCamUp#1]
I'm using an Old 2DS with the latest version of Luma and FastBoot, but the shutter sound is still happening when I take a picture.  I made sure to turn the alarm sound to Off but it's still making the sound

**Comment by TehFridge** [comment]
First. Did you enable game patching in luma?
Second. Did you apply the correct patch and in the correct directory?

**Comment by Anonymous941** [comment]
> First. Did you enable game patching in luma?

Yes, just double-checked...

> Second. Did you apply the correct patch and in the correct directory?

It's in `/luma/sysmodules/0004013000001602.ips`

Also, thanks for making this (even if it's not working atm)!  I've been wondering if this would ever happen

**Comment by TehFridge** [comment]
Weird... It should be working fine if you put it like that. Just to make sure these are my luma settings and patch placement.
For context i also have an old 2ds and it works for me
![IMG_20230831_024404](https://github.com/TehFridge/ShutTheCamUp/assets/85436576/2142ec50-5e84-4c6b-83a5-fb4c37fd489e)
![IMG_20230831_024233](https://github.com/TehFridge/ShutTheCamUp/assets/85436576/5f91936e-9795-45e8-b488-9c7b0e4bfcee)

**Comment by Anonymous941** [comment]
I tried disabling all other modules (which I thought I did before), and it mysteriously started working.  After trying each one, the culprit was `loader.cxi`, which apparently is the un-bricking file which I somehow had on my SD card.  Not sure how, as I never had to recover from a brick...

**Comment by TehFridge** [comment]
Glad the patch works now!
Have fun taking pictures quietly in glorious 640x480!

**Comment by Anonymous941** [comment]
Oh, gosh, that's the resolution...  Well at least they're in 3D, more then I can say for any other camera I own!

**Comment by TehFridge** [comment]
Yup. lol
